import React from 'react';
import { ArrowLeft, Database, Moon, Shield, Server, Layers, User, List, Lock, FileText } from 'lucide-react';

interface RecommendationsProps {
  onBack: () => void;
}

type Category = 'Frontend' | 'Backend';

interface Recommendation {
  icon: any;
  title: string;
  description: string;
  difficulty: 'Low' | 'Medium' | 'High';
  impact: 'Low' | 'Medium' | 'High';
  category: Category;
}

export const Recommendations: React.FC<RecommendationsProps> = ({ onBack }) => {
  const recommendations: Recommendation[] = [
    // Backend (.NET Core Web API)
    {
      icon: Database,
      title: "SQLite Database Integration",
      description: "Replace browser localStorage with a SQLite database via .NET Core Web API to persist user accounts and captured collections.",
      difficulty: "Medium",
      impact: "High",
      category: "Backend"
    },
    {
      icon: Shield,
      title: "JWT Authentication",
      description: "Implement secure login using JWT tokens generated by the Identity Server API. Include role-based access control for Admin/User.",
      difficulty: "Medium",
      impact: "High",
      category: "Backend"
    },
    {
      icon: Server,
      title: "RESTful Resource API",
      description: "Build a .NET Core Web API with EF Core to serve Pokemon data, handle captures, and provide collection statistics.",
      difficulty: "Medium",
      impact: "High",
      category: "Backend"
    },
    {
      icon: Lock,
      title: "Role-Based Authorization",
      description: "Protect CMS endpoints with [Authorize(Roles='Admin')] attribute. Regular users can only read Pokemon and manage their captures.",
      difficulty: "Low",
      impact: "High",
      category: "Backend"
    },
    {
      icon: FileText,
      title: "API Error Handling",
      description: "Return proper IActionResult responses with meaningful error messages for validation failures and exceptions.",
      difficulty: "Low",
      impact: "Medium",
      category: "Backend"
    },

    // Frontend (React + TypeScript)
    {
      icon: User,
      title: "User Registration Page",
      description: "Create a registration form that calls the Identity API to create new user accounts with email and password validation.",
      difficulty: "Low",
      impact: "High",
      category: "Frontend"
    },
    {
      icon: Shield,
      title: "Auth Context & JWT Storage",
      description: "Create an AuthContext provider to manage login state, store JWT in localStorage, and add Authorization headers to API calls.",
      difficulty: "Medium",
      impact: "High",
      category: "Frontend"
    },
    {
      icon: List,
      title: "API Service Integration",
      description: "Refactor pokemonService to call the Resource API instead of PokeAPI. Update all components to use the new data format.",
      difficulty: "Medium",
      impact: "High",
      category: "Frontend"
    },
    {
      icon: Database,
      title: "CMS API Integration",
      description: "Update PokemonCMS to perform real CRUD operations via the Resource API. Add loading states and error handling.",
      difficulty: "Medium",
      impact: "High",
      category: "Frontend"
    },
    {
      icon: Moon,
      title: "Dark Mode Toggle",
      description: "Add a simple dark/light theme toggle using CSS classes. Persist preference in localStorage.",
      difficulty: "Low",
      impact: "Low",
      category: "Frontend"
    },
    {
      icon: Layers,
      title: "Collection Statistics Page",
      description: "Create a page showing capture progress with counts by generation and type. Display simple progress bars.",
      difficulty: "Medium",
      impact: "Medium",
      category: "Frontend"
    }
  ];

  const categories: Category[] = ['Backend', 'Frontend'];

  return (
    <div className="min-h-screen bg-slate-50">
      <header className="bg-indigo-600 text-white shadow-lg sticky top-0 z-30">
        <div className="max-w-7xl mx-auto px-4 h-16 flex items-center gap-4">
          <button onClick={onBack} className="p-2 hover:bg-indigo-700 rounded-full transition-colors">
            <ArrowLeft className="w-5 h-5" />
          </button>
          <h1 className="text-xl font-bold">Project Roadmap</h1>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 py-8">
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden mb-8">
          <div className="p-8 border-b border-slate-100 bg-indigo-50/50">
            <h2 className="text-2xl font-bold text-slate-800 mb-2">Technical Recommendations</h2>
            <p className="text-slate-600 max-w-2xl">
              Focusing strictly on Frontend experiences and Backend integrations (RESTful API) to scale the application.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {categories.map((category) => (
            <div key={category} className="space-y-4">
              <div className="flex items-center gap-3 mb-2">
                <span className={`h-8 w-1 rounded-full ${category === 'Backend' ? 'bg-blue-500' : 'bg-pink-500'
                  }`}></span>
                <h3 className="text-xl font-bold text-slate-800">{category} Development</h3>
              </div>

              <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
                <div className="divide-y divide-slate-100">
                  {recommendations
                    .filter(r => r.category === category)
                    .map((rec, index) => (
                      <div key={index} className="p-5 hover:bg-slate-50 transition-colors group">
                        <div className="flex items-start gap-4">
                          <div className={`p-2.5 rounded-lg flex-shrink-0 group-hover:scale-110 transition-transform ${category === 'Backend' ? 'bg-blue-100 text-blue-600' : 'bg-pink-100 text-pink-600'
                            }`}>
                            <rec.icon className="w-5 h-5" />
                          </div>
                          <div className="flex-1 min-w-0">
                            <div className="flex justify-between items-start mb-1">
                              <h4 className="font-bold text-slate-800 text-sm">{rec.title}</h4>
                            </div>
                            <p className="text-slate-500 text-sm leading-relaxed mb-3">{rec.description}</p>
                            <div className="flex gap-2">
                              <span className={`text-[10px] uppercase tracking-wide font-bold px-2 py-0.5 rounded-full ${rec.difficulty === 'High' ? 'bg-red-50 text-red-600 border border-red-100' :
                                  rec.difficulty === 'Medium' ? 'bg-orange-50 text-orange-600 border border-orange-100' :
                                    'bg-green-50 text-green-600 border border-green-100'
                                }`}>
                                Diff: {rec.difficulty}
                              </span>
                              <span className={`text-[10px] uppercase tracking-wide font-bold px-2 py-0.5 rounded-full ${rec.impact === 'High' ? 'bg-indigo-50 text-indigo-600 border border-indigo-100' :
                                  rec.impact === 'Medium' ? 'bg-blue-50 text-blue-600 border border-blue-100' :
                                    'bg-slate-50 text-slate-600 border border-slate-100'
                                }`}>
                                Impact: {rec.impact}
                              </span>
                            </div>
                          </div>
                        </div>
                      </div>
                    ))}
                </div>
              </div>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
};
